Shopify/blockchain-components

packages/connect-wallet/src/hooks/useConnectWallet/useConnectWalletCallbacks.ts
packages/connect-wallet/src/hooks/useMiddleware.ts
packages/connect-wallet/src/middleware/onConnectMiddleware.test.ts
packages/connect-wallet/src/middleware/onConnectMiddleware.ts
packages/connect-wallet/src/providers/ModalProvider/provider.tsx
packages/connect-wallet/src/slices/walletSlice/walletSlice.test.ts
packages/connect-wallet/src/store/listenerMiddleware.ts
packages/connect-wallet/src/test/configureStore.ts
packages/connect-wallet/src/test/fixtures/connector.ts
packages/connect-wallet/src/test/fixtures/signature.ts
packages/connect-wallet/src/test/fixtures/wallet.ts
packages/connect-wallet/src/types/generics.ts

Refactors and simplifies the `onConnect` listener logic. This allows for easier middleware creation for `onConnect` events by removing the possibility to missed actions (if the actions for `onConnect` logic are to ever change) and DRYs up the creation of listeners.
The inspiration behind this was not only to DRY up the code a bit, but also because in #4 I am going to re-use this logic (it could likely be reused in #13 as well) for looking up ENS names when a wallet connects.
Note: I was going to add tests for `useMiddleware.ts` as well, however I noticed that we need to create some form of app context in order to render hooks with the state provider. I'd prefer for that to be done the right way, and I believe that doing so will make this PR larger than it should be.
Primarily green CI …

[chore] :recycle: Refactor onConnect listener creation to a util function

---

.changeset/thick-fishes-hang.md
packages/gate-context-client/README.md

Adds more detail to the gate context client README so that it appears [on the associated NPM page](https://www.npmjs.com/package/@shopify/gate-context-client).
The [shopify.dev docs](https://shopify.dev/docs/api/blockchain#libraries) were recently updated to include mention of this package, but the link to NPM does not have any documentation. 
I bumped this _patch_ version of the package in order to get NPM to update. LMK if you think that is a problem.
This is just a docs change.

Adds detail to gate context client README

---

.github/workflows/chromatic.yml
packages/connect-wallet/package.json
packages/connect-wallet/src/components/Playground/Playground.stories.tsx
packages/connect-wallet/src/components/index.ts

This PR adds a Playground to Storybook for the `Connect Wallet` package. The idea is to use the tools Storybook provides to enhance the development tools. 
Can be 🎩 in https://639b1f308693132693d9b82c-cafbriamhq.chromatic.com/?path=/story/connect-wallet--playground&args=wallets:Ethereum

[connect-wallet] Add `Playground` story for Connect Wallet package

---

.changeset/gentle-waves-play.md
packages/tokengate/src/components/Tokengate/utils.spec.ts
packages/tokengate/src/providers/TokengateProvider/translations/en/Tokengate.json

As a buyer, I want the specific discount I unlocked to be communicated to me in the tokengate card, after passing a gate
| Before | After |
| -- | -- |
| <img width="414" alt="21-51-drbo3-ghk8f" src="https://user-images.githubusercontent.com/8977776/220484993-6996478c-a4cd-41d6-8787-fc13dc808ec0.png"> | <img width="414" alt="21-51-drbo3-ghk8f" src="https://user-images.githubusercontent.com/8977776/220485040-657fc135-9976-42e2-ad17-1a80335dd0a4.png"> |
Can be 🎩 in https://639b1f308693132693d9b82c-lasslndisp.chromatic.com/?path=/story/tokengate-discount-unlocked--no-order-limit

[tokengate] Show discount on unlocked title

---

.changeset/silver-cougars-check.md
.eslintrc.js
packages/connect-wallet/package.json
packages/connect-wallet/tsconfig.json
packages/shared/package.json
packages/tokengate/package.json
packages/tokengate/src/components/TokenBase/TokenBaseSkeleton.tsx
packages/tokengate/src/fixtures/Condition.ts
packages/tokengate/src/fixtures/Reaction.ts
packages/tokengate/src/fixtures/Requirements.ts
packages/tokengate/src/fixtures/UnlockingToken.ts
packages/tokengate/tsconfig.json

⚠️ Fixes: 
`Dawn`, `Default`, and `Theme` were exported without any information since `packages/shared` is not a published package. 
This leads to issues when attempting to pass a theme value to not only `Tokengate`, but also `ConnectWalletProvider`. Additionally, this makes it impossible to understand the type definition of `Theme` as well as results in errors when attempting to override some values in any of the provided themes.
| Package Name | Before | After |
| - | - | - |
| `@shopify/connect-wallet` |  <img width="503" alt="image" src="https://user-images.githubusercontent.com/4250423/221710224-b7a4a76a-56f8-45bb-b376-6cfdab19fdc0.png"> |  <img width="541" alt="image" src="https://user-images.githubusercontent.com/4250423/221709599-76a0a8d1-13df-4e04-ac9e-65c1a74a44fd.png"> |
| …

:bug: Addresses an issue with exported types from shared

---

.changeset/rude-fishes-smile.md
packages/connect-wallet/src/slices/walletSlice/walletSlice.ts

⚠️ Related: https://github.com/Shopify/blockchain-components/issues/16
Resolves issue for webpack bundlers which cannot resolve path imports
When using the package inside of a framework that utilizes Webpack you will receive an error stating that ethers/lib/utils could not be resolved. While this doesn't resolve _all_ of the errors of this type (redux-persist is another one that uses pathed imports), it is a step in the right direction.
| Before | After |
| - | - |
| <img width="948" alt="image" src="https://user-images.githubusercontent.com/4250423/221713829-51f41b29-9fc7-4ba7-aa32-69ac1b762d0d.png"> |  <img width="929" alt="image" src="https://user-images.githubusercontent.com/4250423/221714457-511e20ac-1df8-49be-9803-a1a25cc97844.png"> |

:bug: Resolves an issue with path imports

---

.changeset/sharp-years-relate.md
packages/gate-context-client/src/cartAjaxApi/cartAjaxApi.ts

Inspecting window on import causes issues with SSR.
When testing using the packages with Next.JS, we saw an error that `window` was not available. `window` is not available on the server-side, but the function referencing it was being invoked at import.
To resolve, we could either check whether window is defined before using it, or move the function call so that it doesn't happen on import. I am doing the latter because there are other functions that check whether window is defined.

Gate context: Moves window inspection on import

---

.changeset/unlucky-days-notice.md
packages/shared/src/index.ts
packages/shared/src/utils/analytics/ClientAnalytics.ts
packages/shared/src/utils/analytics/const.ts
packages/shared/src/utils/analytics/index.ts
packages/shared/src/utils/analytics/types.ts
packages/tokengate/src/components/Tokengate/Tokengate.tsx
packages/tokengate/src/index.ts

Creates a new shared util `ClientAnalytics` based on Hydrogen's [one](https://github.com/Shopify/hydrogen-v1/blob/main/packages/hydrogen/src/foundation/Analytics/ClientAnalytics.tsx#L15).
This new `ClientAnalytics` util function will allow the developers using the components to subscribe to the tracked events and forward the events to their preferred analytics service. 
You can see in this follow-up example how we can use it, having the Playground as an example: https://github.com/Shopify/blockchain-components/pull/40

[analytics] Add `ClientAnalytics` to shared package

---

.changeset/proud-mangos-heal.md
packages/connect-wallet/package.json
packages/connect-wallet/src/middleware/loggerMiddleware.test.ts
packages/connect-wallet/src/middleware/loggerMiddleware.ts
packages/connect-wallet/src/store/configureStore.ts
packages/connect-wallet/src/test/configureStore.ts
yarn.lock

⚠️ Related: #45
Removes `redux-logger` from the package and utilizes our own custom logger middleware. The source for this implementation is a simplified and slimmed down version of the `redux-logger` code that not only matches the types of our store, but also one that we have more control over.
| State (w/ Demo) | Image |
| - | - |
| [Before](https://codesandbox.io/p/sandbox/cocky-jennings-2ttvfj?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A62%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A62%2C%22startLineNumber%22%3A13%7D%5D) | ![SCR-20230302-ng5](https://user-images.githubusercontent.com/4250423/222578316-5371eca0-ffe2-4b8c-b1aa-3b3b59fa458f.png)  |
| [After](https://codesandbox.io/p/sandbox/elegant-silence-6bdexx?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A62%2C …

➖ Removes redux-logger and makes use of custom logger middleware

---

packages/connect-wallet/src/hooks/useConnectorData.test.ts
packages/connect-wallet/src/providers/ConnectWalletProvider/index.ts
packages/connect-wallet/src/providers/ConnectWalletProvider/provider.tsx
packages/connect-wallet/src/test/PackageContext.tsx
packages/connect-wallet/src/test/fixtures/connector.ts
packages/connect-wallet/src/test/fixtures/wagmi.ts
packages/connect-wallet/src/test/utils.tsx

To be able to test the changes made to the `ConnectWalletProvider` in the [Customizable wallet list](https://github.com/Shopify/blockchain-components/pull/55) epic, we need to:
1. Add test infrastructure to be able to test with contexts and test hooks with context. This is also outlined in [this issue](https://github.com/Shopify/nft-gating/issues/1315) and this PR will close it as well. 
2. Test a consumer of `ConnectWalletProvider`, which in this case is the `useConnectorData` hook

Adding test infra for providers and testing useConnectorData

---

.changeset/fifty-carrots-taste.md
packages/connect-wallet/package.json
packages/connect-wallet/tsconfig.json
packages/gate-context-client/package.json
packages/gate-context-client/tsconfig.json
packages/tokengate/package.json
packages/tokengate/tsconfig.json

Removes `tsconfig` and `shared` from package.json for `@shopify/connect-wallet`, `@shopify/gate-context-client` `@shopify/tokengate` to prevent them from being listed as dependencies on NPM (image below).
The goal is to remove `shared` and `tsconfig` from the list of dependencies on npmjs.
<details><summary>Next.js test</summary>
https://user-images.githubusercontent.com/4250423/224126453-4c3339ca-3d74-4fd3-aff9-8097bbe718fd.mov
</details>
<details><summary>Vite test</summary>
https://user-images.githubusercontent.com/4250423/224126649-f0677321-6c2b-4611-a9e8-ec2b4b97195a.mov
</details>

:package: Remove internal packages from dependencies list

---

.changeset/seven-rocks-agree.md
packages/blockchain-components/package.json
packages/blockchain-components/src/utils/cookies/const.ts
packages/blockchain-components/src/utils/cookies/index.ts
packages/blockchain-components/src/utils/cookies/types.ts
packages/blockchain-components/src/utils/cookies/utils.test.ts
packages/blockchain-components/src/utils/cookies/utils.ts
yarn.lock

Adds `util` functions for Shopify cookies. We want to send the session and user token in the analytics published events, these new utils will allow us to get that info.
No demonstration for this PR. We are only adding functions, not calling them yet.
Green CI 🍏

[analytics] Add cookies utils

---

examples/cra/package.json
examples/cra/src/connect-wallet-config.ts
examples/cra/src/index.tsx
packages/connect-wallet/src/types/connector.ts

Refactors the CRA example app to use the new `buildConnectors` function and to pass `connectors` to the `ConnectWalletProvider`. The changes are the same that exist in our [playground](https://github.com/Shopify/blockchain-components/tree/main/apps/playground). 
https://user-images.githubusercontent.com/18248358/225454608-e65bcb60-20e8-4cb6-9cd2-a4a1f4a12783.mov
- Enter the `examples/cra` directory 
- Run `yarn start`
- Verify that the app runs and that you can connect your wallet

Add wallet extensibility changes to CRA example app

---

examples/nextjs/connect-wallet-config.ts
examples/nextjs/package.json
examples/nextjs/pages/_app.tsx

Refactors the Nextjs example app to use the new `buildConnectors` function and to pass `connectors` to the `ConnectWalletProvider`. The changes are the same that exist in our [playground](https://github.com/Shopify/blockchain-components/tree/main/apps/playground). 
https://user-images.githubusercontent.com/18248358/225466443-21e1eb5a-f32e-43c8-b77e-d89f082a4ae5.mov
- Enter the `examples/nextjs` directory 
- Run `yarn dev`
- Verify that the app runs and that you can connect your wallet

Add wallet extensibility changes to Nextjs example app

---

.changeset/ninety-starfishes-admire.md
packages/tokengate/src/components/Tokengate/utils.spec.ts
packages/tokengate/src/components/Tokengate/utils.ts
packages/tokengate/src/components/TokengateRequirements/utils.test.tsx
packages/tokengate/src/components/TokengateRequirements/utils.tsx
packages/tokengate/src/fixtures/Condition.ts
packages/tokengate/src/fixtures/UnlockingToken.ts
packages/tokengate/src/types.ts
packages/tokengate/src/utils/adapters/requirements.ts
packages/tokengate/src/utils/adapters/unlockingTokens.ts

Update tokengate components to use contractAddress instead of collectionAddress
As a 1P developer, I want use `contractAddress` consistently throughout the backend and frontend, so that I reason about the code without coercing values.
**Playground**
https://user-images.githubusercontent.com/18248358/225751290-2dcc6a55-9f85-42dd-9172-926bb85867d1.mov

Refactor `collectionAddress` -> `contractAddress`

---

.changeset/kind-pumpkins-accept.md
packages/connect-wallet/package.json
packages/connect-wallet/src/hooks/useMiddleware.ts
packages/connect-wallet/src/slices/walletSlice/delegateCash.ts
packages/connect-wallet/src/slices/walletSlice/index.ts
packages/connect-wallet/src/slices/walletSlice/walletSlice.ts
packages/connect-wallet/src/types/wallet.ts
yarn.lock

Implements support for [delegate.cash](https://delegate.cash) to allow linking a hot ("delegate") wallet which then looks up associated cold ("vault") wallet(s) that have been proven to be owned by the same entity.
I'll be doing this in different PRs based on the original PR: https://github.com/Shopify/blockchain-components/pull/13
This PR adds the redux logic for supporting delegations.
Can be 🎩 in Replit: https://replit.com/@caropinzonsilva/FamousNonstopAudit
For some reason, the QR codes are not working, so you would need to use Metamask.
- Connect your hot wallet with delegation.
- In the console.log, check the latest redux state
- You should see the `delegationsWalletAddresses` in both the connected wallets and active wallet state:

[delegate-cash] Add redux logic for supporting delegate.cash delegations

---

.changeset/tidy-deers-agree.md
apps/playground/src/index.tsx
packages/connect-wallet/src/hooks/useMiddleware.ts
packages/connect-wallet/src/providers/ConnectWalletProvider/context.tsx
packages/connect-wallet/src/providers/ConnectWalletProvider/provider.tsx
packages/connect-wallet/src/providers/ConnectWalletProvider/types.ts
packages/connect-wallet/src/providers/ModalProvider/provider.tsx

Implements support for [delegate.cash](https://delegate.cash) to allow linking a hot ("delegate") wallet which then looks up associated cold ("vault") wallet(s) that have been proven to be owned by the same entity.
I'll be doing this in different PRs based on the original PR: https://github.com/Shopify/blockchain-components/pull/13
This PR adds a new prop `enableDelegateCash` to the `ConnectWalletProvider` that allows the user to disable the delegate cash support. I'm allowing it by default.
Replit code: https://replit.com/@caropinzonsilva/UnfinishedMeagerPlans
Replit preview: https://unfinishedmeagerplans.caropinzonsilva.repl.co/
- In `ConnectWalletProvider`, set prop `allowDelegateCashSupport` to `true`
- Connect your wallet
- You should see the fetch delegations action getting called
- …

[delegate-cash] Add `enableDelegateCash` prop to ConnectWalletProvider

---

packages/connect-wallet/README.md
packages/gate-context-client/README.md
packages/tokengate/README.md

To ensure we have a single source of truth for the documentation of our packages, we should link to the shopify.dev docs in the READMEs. 
**Pros**
- Single source of truth 
- Easier to maintain 
- Follows Shopify conventions 
- [Connect wallet](https://github.com/Shopify/blockchain-components/blob/docs/link-to-dot-dev-in-readme/packages/connect-wallet/README.md) 
- [Gate context client](https://github.com/Shopify/blockchain-components/blob/docs/link-to-dot-dev-in-readme/packages/gate-context-client/README.md)

Refactor package READMEs to link to shopify.dev docs

---

.changeset/khaki-worms-obey.md
packages/tokengate/src/types.ts

This addresses a minor issue I noticed while writing documentation for the Tokengate package.
Prior to this change, the following was valid:
```tsx
<Tokengate
...
reaction={{
type: 'discount'
}}
/>
```
Notice that the reaction is missing a value for `reaction.discount`.
This change requires `reaction.discount` to be provided when reaction.type is `discount`. Additionally, it prevents `reaction.discount` from being provided as a value when `reaction.type` is `exclusive_access`.
🟢 Green CI

Updates Tokengate reaction type

---

.changeset/lovely-pants-hear.md
packages/connect-wallet/src/hooks/useMiddleware.ts
packages/connect-wallet/src/slices/walletSlice/attributeOrder.test.ts
packages/connect-wallet/src/slices/walletSlice/attributeOrder.ts
packages/connect-wallet/src/slices/walletSlice/delegateCash.ts
packages/connect-wallet/src/slices/walletSlice/walletSlice.ts
packages/gate-context-client/src/cartAjaxApi/cartAjaxApi.ts
packages/gate-context-client/src/types.ts

This PR is a part of the effort to implement delegate cash. 
This PR specifically adds a listener for when the delegations are fetched and then attributes the vault addresses to the order.
**With  `enableDelegateCash` = `true`**
https://user-images.githubusercontent.com/18248358/226959260-a3c5fd5b-27b0-46b4-b8c9-ec2488ba45d7.mov
**With `enableDelegateCash` = `false`**
https://user-images.githubusercontent.com/18248358/226959334-af2d672d-73e6-444a-ba56-5655fc1a06fa.mov
- Set up a delegate.cash account 
- Checkout this branch 
- Add console statements in `attributeOrder` to log the vault address(es) 
- Verify when you connect with your hot wallet, that the vault wallet address(es) are logged
Note: The writing to the cart cannot be tested in the playground as it needs to be tested in the …

[delegate-cash] Attribute vaults to order for delegate cash

---

.changeset/sixty-hotels-unite.md
packages/connect-wallet/src/components/Modal/Modal.tsx
packages/connect-wallet/src/components/Modal/Screens/ConnectScreen.tsx
packages/connect-wallet/src/components/VaultList/VaultList.tsx

Fix delegate-cash components visibility.

[delegate-cash] Fix components visibility logic

---

.changeset/empty-books-sell.md
packages/tokengate/src/components/Tokengate/stories/playground/playground.stories.tsx
packages/tokengate/src/fixtures/Reaction.ts
packages/tokengate/src/types.ts

Our current implementation of the Reaction interface for discounts does not align with the naming conventions used by Shopify Functions. To maintain consistency, we need to update the property name `amount` to `fixedAmount` as per the Shopify Functions reference:
Shopify Functions reference: https://shopify.dev/api/functions/reference/product-discounts/graphql/common-objects/value
- Checkout this branch
- Run `yarn storybook` 
- Verify that the reaction type is `fixedAmount` and the Tokengate card renders correctly

Refactoring `amount` to `fixedAmount`

---

.changeset/fluffy-clocks-listen.md
packages/tokengate/src/components/ButtonWrapper/ButtonWrapper.test.tsx
packages/tokengate/src/components/ButtonWrapper/ButtonWrapper.tsx
packages/tokengate/src/components/ButtonWrapper/utils.test.ts
packages/tokengate/src/components/ButtonWrapper/utils.ts
packages/tokengate/src/components/Tokengate/Tokengate.tsx

During my pairing session with @Borahm we identified that the `active.end` text was rendering with the incorrect color. To address this, I've updated the color prop.
Additionally, we identified an issue where the year was being added to the date string when the year was not the current year. For the time being, this only works for the current year vs following year. It does not calculate based on 365 days. This means that December 31 and January 1 will show a year in the button. 
| Current year | Future year |
| - | - |
| <img width="1182" alt="Screenshot 2023-04-13 at 8 08 40 PM" src="https://user-images.githubusercontent.com/4250423/231915525-62b39cf2-fbcf-4912-ab8f-748b74016c15.png" /> |  <img width="1182" alt="Screenshot 2023-04-13 at 8 08 52 PM" …

🩹 Updated active.end text color and updated i18n options

---

.changeset/spotty-walls-help.md
packages/connect-wallet/src/hooks/useDisconnect.ts
packages/connect-wallet/src/slices/modalSlice/modalSlice.test.ts
packages/connect-wallet/src/slices/modalSlice/modalSlice.ts

Addresses a minor bug that prevented the user from seeing the connector screen inside of the modal after navigating back during the signature flow.
Using a local environment (or the linked Chromatic deployment from CI), you should do the following:
1. Click "Connect Wallet"
2. Click a connector (MetaMask will make the tophatting process much faster)
3. During signing, press the "Back" button in the top of the modal.
4. You **should** be redirected to the first screen within the modal which lists all available connectors.

:bug: Addressed navigate back bug during signature flow

---

.changeset/cool-socks-mix.md
packages/shared/src/components/Popover/Popover.tsx

Addresses misuse of `document.body` inside of the `Popover` component. This was causing errors in some frameworks (such as Remix) where `document` is undefined.
| Before | After |
| - | - |
| <img width="1410" alt="image" src="https://github.com/Shopify/blockchain-components/assets/4250423/999693b2-beec-499c-8306-bbd401e89264" /> | <img width="406" alt="image" src="https://github.com/Shopify/blockchain-components/assets/4250423/a1fdd238-5a7a-49e4-bc79-0793f616d8b4" /> |
You can pull this branch and run the Next.js or Remix example and it should work as expected, but I've also tested in a SSR context with Hydrogen (the after image in the table above) 👀

:bug: Fixes misuse of document.body in Popover component

---

.changeset/quick-coins-reflect.md
packages/connect-wallet/src/hooks/useMiddleware.ts
packages/connect-wallet/src/state/modal/modalState.test.ts
packages/connect-wallet/src/state/modal/modalState.ts
packages/connect-wallet/src/state/types.ts

⚠️ Fixes: #198 
Fixes a bug where after connecting, the modal state is not reset to the clean state meaning that any subsequent attempts (within the same page load) to reconnect would show the connecting state in the modal.
https://github.com/Shopify/blockchain-components/assets/4250423/7f930e54-89ac-4c14-8b28-ee2a93f7fdd9
https://github.com/Shopify/blockchain-components/assets/4250423/8f6a8032-7277-4a12-9605-03eb189036d1
1. Pull the branch and run the playground (`yarn dev`)
2. Connect your wallet
3. Disconnect your wallet
4. Try reconnecting

:bug: Fixes modal state after connection event
